spring:
  application:
    name: server
  datasource:

    #云端数据库
    url: jdbc:mysql://101.126.16.210:3306/xunjian?useSSL=true&serverTimezone=UTC
    username: mysql
    password: aWs7aZYy4fM8TJ2yMB6a
    driver-class-name: com.mysql.cj.jdbc.Driver

#    # 本地数据库
#    url: jdbc:mysql://localhost:3306/xunjian?useSSL=true&serverTimezone=UTC
#    username: root
#    password: 929260.sjq
#    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  devtools:
    restart:
      additional-paths: src/main/resources/static
    resources:
      cache:
        period: 0
#  data:
#    mongodb:
#      host: ironpillar.top
#      port: 27017
#      database: file_storage
#      username: pillar
#      password: "929260.sjq"
#      authentication-database: admin
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
  mapper-locations: classpath:/mapper/**/*.xml

app:
  login:
    expire-time: 100000 # 登录过期时间，小时
  jwt:
    key: KKCMyBerAAjBbbtHj4KG # jwt加密密钥
  user:
    isp-pos-valid-time: 100000000 # 巡检人员位置信息的有效时间（单位：分钟）
    system-user-default-password: 123456 # 系统用户默认密码
  xunjian-point:
    time-limit: 1200000 # 巡检点最大间隔时间（分钟）
    distance-limit: 10 # 巡检点间最大距离（千米）

internal-communication:
  common:
    relay-time-window-s: 600 # 秒
  xunjian-server-mobile:
    app-id: "xunjian-server-mobile"
    secret: "6a33d1de-b580-4b27-9312-ad6a2e1d967b"
    url: "localhost"
    port: "8082"
  xunjian-server-web:
    protocol: "http"
    app-id: "xunjian-server-web"
    secret: "70eb394e-a98c-4c29-aa12-55571428ef63"
    url: "localhost"
    port: "8080"
    isp-pos-update-path: "/internal/update/isp-pos-update"
